// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/tukano/api/grpc/Blobs.proto

package tukano.impl.grpc.generated_java;

public final class BlobsProtoBuf {
  private BlobsProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UploadArgsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UploadArgs)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string blobId = 1;</code>
     * @return The blobId.
     */
    java.lang.String getBlobId();
    /**
     * <code>string blobId = 1;</code>
     * @return The bytes for blobId.
     */
    com.google.protobuf.ByteString
        getBlobIdBytes();

    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code UploadArgs}
   */
  public static final class UploadArgs extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UploadArgs)
      UploadArgsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UploadArgs.newBuilder() to construct.
    private UploadArgs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UploadArgs() {
      blobId_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UploadArgs();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UploadArgs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              blobId_ = s;
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_UploadArgs_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_UploadArgs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs.class, tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs.Builder.class);
    }

    public static final int BLOBID_FIELD_NUMBER = 1;
    private volatile java.lang.Object blobId_;
    /**
     * <code>string blobId = 1;</code>
     * @return The blobId.
     */
    @java.lang.Override
    public java.lang.String getBlobId() {
      java.lang.Object ref = blobId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        blobId_ = s;
        return s;
      }
    }
    /**
     * <code>string blobId = 1;</code>
     * @return The bytes for blobId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBlobIdBytes() {
      java.lang.Object ref = blobId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blobId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blobId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, blobId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blobId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, blobId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs)) {
        return super.equals(obj);
      }
      tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs other = (tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs) obj;

      if (!getBlobId()
          .equals(other.getBlobId())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOBID_FIELD_NUMBER;
      hash = (53 * hash) + getBlobId().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UploadArgs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UploadArgs)
        tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_UploadArgs_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_UploadArgs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs.class, tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs.Builder.class);
      }

      // Construct using tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        blobId_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_UploadArgs_descriptor;
      }

      @java.lang.Override
      public tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs getDefaultInstanceForType() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs.getDefaultInstance();
      }

      @java.lang.Override
      public tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs build() {
        tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs buildPartial() {
        tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs result = new tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs(this);
        result.blobId_ = blobId_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs) {
          return mergeFrom((tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs other) {
        if (other == tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs.getDefaultInstance()) return this;
        if (!other.getBlobId().isEmpty()) {
          blobId_ = other.blobId_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object blobId_ = "";
      /**
       * <code>string blobId = 1;</code>
       * @return The blobId.
       */
      public java.lang.String getBlobId() {
        java.lang.Object ref = blobId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          blobId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string blobId = 1;</code>
       * @return The bytes for blobId.
       */
      public com.google.protobuf.ByteString
          getBlobIdBytes() {
        java.lang.Object ref = blobId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          blobId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string blobId = 1;</code>
       * @param value The blobId to set.
       * @return This builder for chaining.
       */
      public Builder setBlobId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        blobId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string blobId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlobId() {
        
        blobId_ = getDefaultInstance().getBlobId();
        onChanged();
        return this;
      }
      /**
       * <code>string blobId = 1;</code>
       * @param value The bytes for blobId to set.
       * @return This builder for chaining.
       */
      public Builder setBlobIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        blobId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UploadArgs)
    }

    // @@protoc_insertion_point(class_scope:UploadArgs)
    private static final tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs();
    }

    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UploadArgs>
        PARSER = new com.google.protobuf.AbstractParser<UploadArgs>() {
      @java.lang.Override
      public UploadArgs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UploadArgs(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UploadArgs> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UploadArgs> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadArgs getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UploadResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UploadResult)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code UploadResult}
   */
  public static final class UploadResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UploadResult)
      UploadResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UploadResult.newBuilder() to construct.
    private UploadResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UploadResult() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UploadResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UploadResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_UploadResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_UploadResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult.class, tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult)) {
        return super.equals(obj);
      }
      tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult other = (tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UploadResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UploadResult)
        tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_UploadResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_UploadResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult.class, tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult.Builder.class);
      }

      // Construct using tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_UploadResult_descriptor;
      }

      @java.lang.Override
      public tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult getDefaultInstanceForType() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult.getDefaultInstance();
      }

      @java.lang.Override
      public tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult build() {
        tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult buildPartial() {
        tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult result = new tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult) {
          return mergeFrom((tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult other) {
        if (other == tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UploadResult)
    }

    // @@protoc_insertion_point(class_scope:UploadResult)
    private static final tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult();
    }

    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UploadResult>
        PARSER = new com.google.protobuf.AbstractParser<UploadResult>() {
      @java.lang.Override
      public UploadResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UploadResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UploadResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UploadResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tukano.impl.grpc.generated_java.BlobsProtoBuf.UploadResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DownloadArgsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DownloadArgs)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string blobId = 1;</code>
     * @return The blobId.
     */
    java.lang.String getBlobId();
    /**
     * <code>string blobId = 1;</code>
     * @return The bytes for blobId.
     */
    com.google.protobuf.ByteString
        getBlobIdBytes();
  }
  /**
   * Protobuf type {@code DownloadArgs}
   */
  public static final class DownloadArgs extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DownloadArgs)
      DownloadArgsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DownloadArgs.newBuilder() to construct.
    private DownloadArgs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DownloadArgs() {
      blobId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DownloadArgs();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DownloadArgs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              blobId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_DownloadArgs_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_DownloadArgs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs.class, tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs.Builder.class);
    }

    public static final int BLOBID_FIELD_NUMBER = 1;
    private volatile java.lang.Object blobId_;
    /**
     * <code>string blobId = 1;</code>
     * @return The blobId.
     */
    @java.lang.Override
    public java.lang.String getBlobId() {
      java.lang.Object ref = blobId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        blobId_ = s;
        return s;
      }
    }
    /**
     * <code>string blobId = 1;</code>
     * @return The bytes for blobId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBlobIdBytes() {
      java.lang.Object ref = blobId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blobId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blobId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, blobId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blobId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, blobId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs)) {
        return super.equals(obj);
      }
      tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs other = (tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs) obj;

      if (!getBlobId()
          .equals(other.getBlobId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOBID_FIELD_NUMBER;
      hash = (53 * hash) + getBlobId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DownloadArgs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DownloadArgs)
        tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_DownloadArgs_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_DownloadArgs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs.class, tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs.Builder.class);
      }

      // Construct using tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        blobId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_DownloadArgs_descriptor;
      }

      @java.lang.Override
      public tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs getDefaultInstanceForType() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs.getDefaultInstance();
      }

      @java.lang.Override
      public tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs build() {
        tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs buildPartial() {
        tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs result = new tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs(this);
        result.blobId_ = blobId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs) {
          return mergeFrom((tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs other) {
        if (other == tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs.getDefaultInstance()) return this;
        if (!other.getBlobId().isEmpty()) {
          blobId_ = other.blobId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object blobId_ = "";
      /**
       * <code>string blobId = 1;</code>
       * @return The blobId.
       */
      public java.lang.String getBlobId() {
        java.lang.Object ref = blobId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          blobId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string blobId = 1;</code>
       * @return The bytes for blobId.
       */
      public com.google.protobuf.ByteString
          getBlobIdBytes() {
        java.lang.Object ref = blobId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          blobId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string blobId = 1;</code>
       * @param value The blobId to set.
       * @return This builder for chaining.
       */
      public Builder setBlobId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        blobId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string blobId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlobId() {
        
        blobId_ = getDefaultInstance().getBlobId();
        onChanged();
        return this;
      }
      /**
       * <code>string blobId = 1;</code>
       * @param value The bytes for blobId to set.
       * @return This builder for chaining.
       */
      public Builder setBlobIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        blobId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DownloadArgs)
    }

    // @@protoc_insertion_point(class_scope:DownloadArgs)
    private static final tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs();
    }

    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DownloadArgs>
        PARSER = new com.google.protobuf.AbstractParser<DownloadArgs>() {
      @java.lang.Override
      public DownloadArgs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DownloadArgs(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DownloadArgs> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DownloadArgs> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadArgs getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DownloadResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DownloadResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes chunk = 1;</code>
     * @return The chunk.
     */
    com.google.protobuf.ByteString getChunk();
  }
  /**
   * Protobuf type {@code DownloadResult}
   */
  public static final class DownloadResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DownloadResult)
      DownloadResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DownloadResult.newBuilder() to construct.
    private DownloadResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DownloadResult() {
      chunk_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DownloadResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DownloadResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              chunk_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_DownloadResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_DownloadResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult.class, tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult.Builder.class);
    }

    public static final int CHUNK_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString chunk_;
    /**
     * <code>bytes chunk = 1;</code>
     * @return The chunk.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getChunk() {
      return chunk_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!chunk_.isEmpty()) {
        output.writeBytes(1, chunk_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!chunk_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, chunk_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult)) {
        return super.equals(obj);
      }
      tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult other = (tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult) obj;

      if (!getChunk()
          .equals(other.getChunk())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHUNK_FIELD_NUMBER;
      hash = (53 * hash) + getChunk().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DownloadResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DownloadResult)
        tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_DownloadResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_DownloadResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult.class, tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult.Builder.class);
      }

      // Construct using tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        chunk_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.internal_static_DownloadResult_descriptor;
      }

      @java.lang.Override
      public tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult getDefaultInstanceForType() {
        return tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult.getDefaultInstance();
      }

      @java.lang.Override
      public tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult build() {
        tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult buildPartial() {
        tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult result = new tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult(this);
        result.chunk_ = chunk_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult) {
          return mergeFrom((tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult other) {
        if (other == tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult.getDefaultInstance()) return this;
        if (other.getChunk() != com.google.protobuf.ByteString.EMPTY) {
          setChunk(other.getChunk());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString chunk_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes chunk = 1;</code>
       * @return The chunk.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getChunk() {
        return chunk_;
      }
      /**
       * <code>bytes chunk = 1;</code>
       * @param value The chunk to set.
       * @return This builder for chaining.
       */
      public Builder setChunk(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chunk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes chunk = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChunk() {
        
        chunk_ = getDefaultInstance().getChunk();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DownloadResult)
    }

    // @@protoc_insertion_point(class_scope:DownloadResult)
    private static final tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult();
    }

    public static tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DownloadResult>
        PARSER = new com.google.protobuf.AbstractParser<DownloadResult>() {
      @java.lang.Override
      public DownloadResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DownloadResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DownloadResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DownloadResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tukano.impl.grpc.generated_java.BlobsProtoBuf.DownloadResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadArgs_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UploadArgs_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UploadResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DownloadArgs_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DownloadArgs_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DownloadResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DownloadResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/tukano/api/grpc/Blobs.proto\"*\n\nUpl" +
      "oadArgs\022\016\n\006blobId\030\001 \001(\t\022\014\n\004data\030\002 \001(\014\"\016\n" +
      "\014UploadResult\"\036\n\014DownloadArgs\022\016\n\006blobId\030" +
      "\001 \001(\t\"\037\n\016DownloadResult\022\r\n\005chunk\030\001 \001(\0142_" +
      "\n\005Blobs\022&\n\006upload\022\013.UploadArgs\032\r.UploadR" +
      "esult\"\000\022.\n\010download\022\r.DownloadArgs\032\017.Dow" +
      "nloadResult\"\0000\001B0\n\037tukano.impl.grpc.gene" +
      "rated_javaB\rBlobsProtoBufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UploadArgs_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UploadArgs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UploadArgs_descriptor,
        new java.lang.String[] { "BlobId", "Data", });
    internal_static_UploadResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UploadResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UploadResult_descriptor,
        new java.lang.String[] { });
    internal_static_DownloadArgs_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DownloadArgs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DownloadArgs_descriptor,
        new java.lang.String[] { "BlobId", });
    internal_static_DownloadResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DownloadResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DownloadResult_descriptor,
        new java.lang.String[] { "Chunk", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
